Bneukom/undo redo fix
Esri/vitruvio pull request #106
Opened 2022-10-31 09:10 UTC by bneukom

2022-11-04 08:31 UTC, chr11115 requested changes
Nice work! I noticed some minor behavior changes, please check if they were intentional or not. Otherwise only some minor comments

2022-11-04 08:31 UTC, chr11115 commented on VitruvioHost/Plugins/Vitruvio/Source/VitruvioEditor/Private/VitruvioEditorModule.cpp
> +	const FTransaction* LastTransaction = GEditor->Trans->GetTransaction(GEditor->Trans->GetQueueLength() - 1);
This entire function setup looks really hacky to me. If we really need to do call PostUndoRedo later again could we not simply schedule the undo/redo call from within the component (e.g. by adding it to a list, setting a flag ect..) and then calling postUndoRedo on the marked components?

2022-11-10 12:34 UTC, bneukom commented on VitruvioHost/Plugins/Vitruvio/Source/Vitruvio/Private/InitialShape.cpp
> +			if (UVitruvioComponent* VitruvioComponent = Owner->FindComponentByClass<UVitruvioComponent>())
This function is overriden from `UObject` so we can't pass it.

2022-11-10 12:35 UTC, bneukom commented on VitruvioHost/Plugins/Vitruvio/Source/Vitruvio/Private/VitruvioComponent.cpp
> +		Child->DestroyComponent(false);
Good point. Will change that!

2022-11-11 08:32 UTC, bneukom commented on VitruvioHost/Plugins/Vitruvio/Source/Vitruvio/Private/InitialShape.cpp
> +	StaticMeshComponent->SetStaticMesh(StaticMesh);
Good catch! I think that was some wrong left over code.

2022-11-11 09:05 UTC, bneukom commented on VitruvioHost/Plugins/Vitruvio/Source/Vitruvio/Private/InitialShape.cpp
> +		Polygon = CreateDefaultInitialShapePolygon();
Good catch. No that was not intentional. I'll take your proposed code :)

2022-11-11 09:11 UTC, bneukom commented on VitruvioHost/Plugins/Vitruvio/Source/Vitruvio/Private/InitialShape.cpp
> +		Polygon = CreateDefaultInitialShapePolygon();
I think this version is fine because we don't have a check in the first if? It will always set the poylgon.

2022-11-11 09:21 UTC, bneukom commented on VitruvioHost/Plugins/Vitruvio/Source/Vitruvio/Private/InitialShape.cpp
> +		if (OldPolygon != Polygon)
Yes I think it makes sense that null static meshes result in an empty polygon. I made the code a bit clearer to reflect that.

2022-11-15 16:05 UTC, chr11115 approved these changes
LGTM :)

Just a minor note: 
I think the previous behavior when resetting the initial shape to null was to create a default quad. After your initial changes resetting the initial shape would do nothing (i.e. keep the last valid initial shape polygon) and now we actually reset the initial shape to an empty polygon. 

I think the new behavior is actually what should be expected imo and therefore I think this is fine 👍

2022-11-17 08:52 UTC, merged